language: node_js
sudo: false
notifications:
  email:
    recipients:
      - sebastien.jourdain@kitware.com
      - ken.martin@kitware.com
      - scott.wittenburg@kitware.com
    on_success: change
    on_failure: always
cache:
  directories:
    - node_modules
    - Documentation/build-tmp
env:
  - CXX=g++-4.8
addons:
  sources:
    - ubuntu-toolchain-r-test
  apt:
    packages:
      - g++-4.8
      - mesa-utils
      - xvfb
      - libgl1-mesa-dri
      - libglapi-mesa
      - libosmesa6
before_script:
  - export DISPLAY=:99.0; sh -e /etc/init.d/xvfb start
node_js:
  - "5.1"
script:
  - npm install
  - npm run build:release
  - npm run test:travis
  - git config --global user.name "Travis CI"
  - git config --global user.email "sebastien.jourdain@kitware.com"
  - export GIT_PUBLISH_URL=https://${GH_TOKEN}@github.com/Kitware/vtk-js.git
  - if [ "$TRAVIS_BRANCH" == "master" ]; then npm run doc:publish; fi
branches:
  except:
    - "/^v\\d+\\.\\d+\\.\\d+$/"
